[package]
name = "spartan"
version = "0.1.0"
edition = "2021"

[dependencies]
walkdir = "2.4"
fs_extra = "1.3"
clap = { version = "4.5", features = ["derive"] }
log = "0.4"
env_logger = "0.10"
anyhow = "1.0"
